/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    DatePicker: typeof import('./src/components/ui/DatePicker.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('./src/components/ui/FileUpload.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LegendCard: typeof import('./src/components/legends/LegendCard.vue')['default']
    LegendFilter: typeof import('./src/components/legends/LegendFilter.vue')['default']
    LegendForm: typeof import('./src/components/legends/LegendForm.vue')['default']
    LegendListView: typeof import('./src/components/legends/LegendListView.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
