services:
  vue-app:
    build: .
    container_name: vue-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend-network

volumes:
  node_modules:
networks:
  frontend-network:
    driver: bridge
