services:
  vue-app:
    build: .
    container_name: vue-app
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
